[theme]
base = "dark"
backgroundColor = "#0b0f2a"
secondaryBackgroundColor = "#111535"
primaryColor = "#00d4ff"
textColor = "#dde3ed"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false
